# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_studente_cellulare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField()),
                ('aula', models.TextField()),
                ('descrizione', models.TextField()),
                ('host', models.TextField(verbose_name='Tenuto da ')),
                ('iscritti_massimi', models.PositiveIntegerField()),
                ('iscritti', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Iscritto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperi.Gruppo')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscritti_recuperi', to='accounts.Studente')),
            ],
        ),
        migrations.CreateModel(
            name='Settimana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('mostra_settimana', models.DateField()),
                ('nascondi_settimana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.TimeField(verbose_name='Orario di inizio')),
                ('orario_fine', models.TimeField(verbose_name='Fine turno')),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperi.Giorno')),
            ],
        ),
        migrations.AddField(
            model_name='gruppo',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperi.Turno'),
        ),
        migrations.AddField(
            model_name='giorno',
            name='settimana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperi.Settimana'),
        ),
    ]
