# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperi', '0005_gruppo_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppo',
            name='sede',
            field=models.TextField(choices=[('Sede', 'Sede Viale Pepoli'), ('Succursale', 'Succursale Via Tolmino')], default='Sede'),
        ),
    ]
