# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:06
from __future__ import unicode_literals

import accounts.custom_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('classe', accounts.custom_models.IntegerRangeField()),
                ('sezione', accounts.custom_models.UpperCharField(max_length=1)),
                ('is_rappr_classe', models.BooleanField(default=False)),
                ('is_rappr_istituto', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
