# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 16:54
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studente',
            name='cellulare',
            field=phonenumber_field.modelfields.PhoneNumberField(default='330000000', max_length=128),
            preserve_default=False,
        ),
    ]
