# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=15)),
                ('studenti_max', models.PositiveIntegerField(verbose_name='Numero massimo studenti')),
                ('n_studenti', models.PositiveIntegerField(blank=True, null=True)),
                ('prima', models.BooleanField(default=True)),
                ('seconda', models.BooleanField(default=True)),
                ('terza', models.BooleanField(default=True)),
                ('quarta', models.BooleanField(default=True)),
                ('quinta', models.BooleanField(default=True)),
                ('approvato', models.BooleanField(default=False)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Studente')),
            ],
        ),
    ]
