# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 16:55
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20160831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cellulare',
            field=phonenumber_field.modelfields.PhoneNumberField(default='3000000000', max_length=128),
            preserve_default=False,
        ),
    ]
