# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_auto_20160831_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cellulare',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Il numero di telefono deve essere inserito in questo formato: '+999999999'. Hai aggiunto il +39?", regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Numero di cellulare'),
        ),
    ]
