# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilancio', '0002_bilanciomensilefondo_descrizione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanciomensilefondo',
            name='mese',
        ),
        migrations.AddField(
            model_name='bilanciomensilefondo',
            name='data',
            field=models.DateField(default='2016-01-01'),
            preserve_default=False,
        ),
    ]
