# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assemblea', models.DateField()),
                ('sede', models.CharField(max_length=150)),
                ('mostra_assemblea', models.DateField()),
                ('nascondi_assemblea', models.DateField()),
            ],
            options={
                'permissions': (('can_add_assemblea', "Può aggiungere un'assemblea"), ('can_edit_assemblea', "Può modificare un'assemblea"), ('can_delete_assemblea', "Può rimuovere un'assemblea")),
            },
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField()),
                ('aula', models.TextField()),
                ('descrizione', models.TextField()),
                ('host', models.TextField(verbose_name='Tenuto da ')),
                ('iscritti_massimi', models.PositiveIntegerField()),
                ('iscritti', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Iscritto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblee.Gruppo')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscritti', to='accounts.Studente')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.TimeField(verbose_name='Orario di inizio')),
                ('orario_fine', models.TimeField(verbose_name='Fine turno')),
                ('assemblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblee.Assemblea')),
            ],
        ),
        migrations.AddField(
            model_name='gruppo',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assemblee.Turno'),
        ),
    ]
